import './globals.css'
import Navbar from './components/Navbar/index'
import Footer from './components/Footer/index'
import SmoothScroll from './components/SmoothScroll/index'
import PopupBannerWrapper from './components/PopupBannerWrapper'

export const metadata = {
  title: 'Posspole Catalyst',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined') {
                window.addEventListener('beforeunload', function() {
                  window.scrollTo(0, 0);
                });
                
                window.addEventListener('load', function() {
                  window.scrollTo(0, 0);
                });
              }
            `,
          }}
        />
        <PopupBannerWrapper 
          imageSrc="/images/banner.png"
          imageAlt="Program Registration Banner"
          autoShow={true}
          showDelay={1500}
        />
        <Navbar />
        <SmoothScroll>
          {children}
        </SmoothScroll>
        <Footer />
      </body>
    </html>
  )
}
