import './styles.css';
import { Nunito } from 'next/font/google';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/index';
import ScrollEffect from './components/ScrollEffect/index';
import SmoothScroll from './components/SmoothScroll/index';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: 'Posspole catalyst',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ScrollEffect />
        <SmoothScroll />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
